import { describe, expect, it } from "vitest";
import { analyzeCoauthor, isAiCommit } from "~/analyzers/coauthor";
import type { GitHubCommit } from "~/github/types";

describe("isAiCommit", () => {
	it("detects Co-Authored-By with known AI name", () => {
		expect(
			isAiCommit(
				"feat: add\n\nCo-Authored-By: Claude <noreply@anthropic.com>",
				null,
			),
		).toBe(true);
	});

	it("does NOT match Co-Authored-By with human name", () => {
		expect(
			isAiCommit("feat: pair\n\nCo-Authored-By: John <john@example.com>", null),
		).toBe(false);
	});

	it("detects Generated by pattern", () => {
		expect(isAiCommit("fix: bug\n\nGenerated by Cursor", null)).toBe(true);
	});

	it("detects AI emoji pattern", () => {
		expect(isAiCommit("🤖 automated commit", null)).toBe(true);
	});

	it("detects [AI] tag", () => {
		expect(isAiCommit("[AI] refactor module", null)).toBe(true);
	});

	it("returns false for normal commit", () => {
		expect(isAiCommit("fix: update readme", null)).toBe(false);
	});

	it("detects known bot author login", () => {
		expect(isAiCommit("fix: auto-fix", "devin-ai-integration[bot]")).toBe(true);
	});

	it("detects sweep bot", () => {
		expect(isAiCommit("fix: something", "sweep-ai[bot]")).toBe(true);
	});

	it("does not flag normal user as bot", () => {
		expect(isAiCommit("fix: something", "regularuser")).toBe(false);
	});
});

describe("analyzeCoauthor", () => {
	let oidCounter = 0;
	const makeCommit = (
		message: string,
		login: string | null = "testuser",
	): GitHubCommit => ({
		oid: `sha-${++oidCounter}`,
		message,
		committedDate: "2026-03-14T00:00:00Z",
		author: { user: login ? { login } : null },
	});

	it("calculates rate across all repos", () => {
		const commits = [
			makeCommit("feat: add\n\nCo-Authored-By: Claude <noreply@anthropic.com>"),
			makeCommit("fix: bug"),
			makeCommit("🤖 automated"),
			makeCommit("docs: update"),
		];
		const result = analyzeCoauthor(commits);
		expect(result.totalCommits).toBe(4);
		expect(result.aiCommits).toBe(2);
		expect(result.rate).toBe(0.5);
	});

	it("detects bot author commits", () => {
		const commits = [
			makeCommit("fix: auto-fix", "devin-ai-integration[bot]"),
			makeCommit("fix: normal", "humanuser"),
		];
		const result = analyzeCoauthor(commits);
		expect(result.aiCommits).toBe(1);
	});

	it("handles empty commits", () => {
		const result = analyzeCoauthor([]);
		expect(result.totalCommits).toBe(0);
		expect(result.aiCommits).toBe(0);
		expect(result.rate).toBe(0);
	});
});
