export interface AiDetection {
  isAi: boolean
  toolId: string
}

interface Signal {
  pattern: RegExp
  toolId: string
}

// author login 由来のシグナル。順序が優先度（具体的な bot → 汎用 [bot]）
const BOT_SIGNALS: Signal[] = [
  { pattern: /^copilot-for-prs\[bot\]$/, toolId: 'copilot' },
  { pattern: /^copilot-swe-agent\[bot\]$/, toolId: 'copilot' },
  // [bot] 必須（人間ユーザーが偶然 devin-ai/sweep-ai で始まるログイン名を誤って
  // 具体ツールへ帰属させないため。旧 attributeTool の完全一致相当の精度を維持）
  { pattern: /^devin-ai.*\[bot\]$/, toolId: 'devin' },
  { pattern: /^sweep-ai.*\[bot\]$/, toolId: 'sweep' },
  { pattern: /^dependabot/, toolId: 'unknown' },
  { pattern: /^renovate/, toolId: 'unknown' },
  { pattern: /^github-actions/, toolId: 'unknown' },
  { pattern: /\[bot\]$/, toolId: 'unknown' },
]

// メッセージ由来のシグナル。順序が優先度（ツール特定可能 → 汎用AIマーカー）。
// 検出パターンと toolId 帰属の単一テーブル — ここに追加すれば isAiCommit と
// attributeTool の両方に同時に効く（契約不一致の構造的排除）
const MESSAGE_SIGNALS: Signal[] = [
  // ベンダードメイン単独（@anthropic.com 等）では判定しない（人間の社員 co-author を
  // 誤検出するため、ドメインの scoping 有無に関わらず全て除外し名称一致のみに統一）
  {
    pattern:
      /co-authored-by:.*\bclaude\b|assisted-by:.*\bclaude\b|generated with \[?claude( code)?\]?|via claude\b/i,
    toolId: 'claude',
  },
  { pattern: /co-authored-by:.*\bcodex\b|via codex\b/i, toolId: 'codex' },
  { pattern: /co-authored-by:.*\bcopilot\b|assisted-by:.*\bcopilot\b/i, toolId: 'copilot' },
  {
    pattern: /co-authored-by:.*\bcursor\b|generated with cursor\b|via cursor\b/i,
    toolId: 'cursor',
  },
  { pattern: /co-authored-by:.*\b(windsurf|codeium)\b/i, toolId: 'windsurf' },
  { pattern: /co-authored-by:.*\baider\b|via aider\b/i, toolId: 'aider' },
  { pattern: /co-authored-by:.*\btabnine\b/i, toolId: 'tabnine' },
  { pattern: /co-authored-by:.*\b(cody|sourcegraph)\b/i, toolId: 'cody' },
  { pattern: /co-authored-by:.*\b(amazon-?q|amazonq)\b/i, toolId: 'amazonq' },
  {
    // @google.com 単独では判定しない（人間の Google 社員 co-author を誤検出するため）。
    // 明示的な gemini 表記がある場合のみ検出
    pattern: /co-authored-by:.*\bgemini\b|assisted-by:.*\bgemini\b/i,
    toolId: 'gemini',
  },
  { pattern: /co-authored-by:.*\bdevin\b|via devin\b/i, toolId: 'devin' },
  { pattern: /co-authored-by:.*\bsweep\b/i, toolId: 'sweep' },
  // ---- 汎用AIマーカー（AI とは判るがツール特定不能 = 正当な unknown）----
  { pattern: /co-authored-by:\s.*\d+\+[^@]+@users\.noreply\.github\.com/i, toolId: 'unknown' },
  { pattern: /co-authored-by:\s.*noreply@/i, toolId: 'unknown' },
  // 'with' を含めると通常のコード生成ツール（openapi-generator/protoc等）の
  // commit message を誤検出するため 'by' のみに限定
  { pattern: /generated by/i, toolId: 'unknown' },
  { pattern: /\[ai\]/i, toolId: 'unknown' },
  { pattern: /🤖/, toolId: 'unknown' },
]

export function detectAiSignal(message: string, authorLogin: string | null): AiDetection {
  if (authorLogin) {
    for (const s of BOT_SIGNALS) {
      if (s.pattern.test(authorLogin)) return { isAi: true, toolId: s.toolId }
    }
  }
  for (const s of MESSAGE_SIGNALS) {
    if (s.pattern.test(message)) return { isAi: true, toolId: s.toolId }
  }
  return { isAi: false, toolId: 'unknown' }
}

// assisted シグナル: コミット本文で AI をレビュアー的に使った文脈（ツール名 + 使用動詞の
// 隣接）を拾う。トレーラーを残さないレビュー用途（codex exec review 等）を可視化する。
// ツール名単独では絶対にマッチさせない — 「add Codex tool detection」「Codex対応」のような
// 言及・機能追加コミットは非マッチ（使用動詞との隣接文脈が必須）。順序 = 優先度。
const ASSISTED_SIGNALS: Signal[] = [
  {
    pattern:
      /codex\s*(exec\s*)?(review|レビュー|指摘|plan\s*レビュー)|codexレビュー|\(codex\s*#?\d|per\s+codex|codex\s+(flagged|found|caught|suggested)/i,
    toolId: 'codex',
  },
  // gpt-4/gpt-5 系のレビュー言及はこのプロジェクト文脈では codex 経由。'chatgpt' toolId は作らない
  {
    pattern:
      /gpt-?[45][\w.-]*\s*(review|レビュー|指摘)|gpt-?[45][\w.-]*\s+(flagged|found|caught|suggested)/i,
    toolId: 'codex',
  },
  {
    pattern:
      /claude\s*(review|レビュー|指摘)|claudeレビュー|per\s+claude|claude\s+(flagged|found|caught|suggested)/i,
    toolId: 'claude',
  },
  {
    pattern:
      /copilot\s*(review|レビュー|指摘)|copilotレビュー|copilot\s+(flagged|found|caught|suggested)/i,
    toolId: 'copilot',
  },
  {
    pattern:
      /cursor\s*(review|レビュー|指摘)|cursorレビュー|cursor\s+(flagged|found|caught|suggested)/i,
    toolId: 'cursor',
  },
  {
    pattern:
      /gemini\s*(review|レビュー|指摘)|geminiレビュー|gemini\s+(flagged|found|caught|suggested)/i,
    toolId: 'gemini',
  },
  {
    pattern:
      /aider\s*(review|レビュー|指摘)|aiderレビュー|aider\s+(flagged|found|caught|suggested)/i,
    toolId: 'aider',
  },
]

export function detectAssistedSignal(message: string): string | null {
  for (const s of ASSISTED_SIGNALS) {
    if (s.pattern.test(message)) return s.toolId
  }
  return null
}
