export interface AiDetection {
  isAi: boolean
  toolId: string
}

interface Signal {
  pattern: RegExp
  toolId: string
}

// author login 由来のシグナル。順序が優先度（具体的な bot → 汎用 [bot]）
const BOT_SIGNALS: Signal[] = [
  { pattern: /^copilot-for-prs\[bot\]$/, toolId: 'copilot' },
  { pattern: /^copilot-swe-agent\[bot\]$/, toolId: 'copilot' },
  // [bot] 必須（人間ユーザーが偶然 devin-ai/sweep-ai で始まるログイン名を誤って
  // 具体ツールへ帰属させないため。旧 attributeTool の完全一致相当の精度を維持）
  { pattern: /^devin-ai.*\[bot\]$/, toolId: 'devin' },
  { pattern: /^sweep-ai.*\[bot\]$/, toolId: 'sweep' },
  { pattern: /^dependabot/, toolId: 'unknown' },
  { pattern: /^renovate/, toolId: 'unknown' },
  { pattern: /^github-actions/, toolId: 'unknown' },
  { pattern: /\[bot\]$/, toolId: 'unknown' },
]

// メッセージ由来のシグナル。順序が優先度（ツール特定可能 → 汎用AIマーカー）。
// 検出パターンと toolId 帰属の単一テーブル — ここに追加すれば isAiCommit と
// attributeTool の両方に同時に効く（契約不一致の構造的排除）
const MESSAGE_SIGNALS: Signal[] = [
  // ベンダードメイン単独（@anthropic.com 等）では判定しない（人間の社員 co-author を
  // 誤検出するため、ドメインの scoping 有無に関わらず全て除外し名称一致のみに統一）
  {
    pattern: /co-authored-by:.*\bclaude\b|assisted-by:.*\bclaude\b|generated with \[?claude( code)?\]?|via claude\b/i,
    toolId: 'claude',
  },
  { pattern: /co-authored-by:.*\bcodex\b|via codex\b/i, toolId: 'codex' },
  { pattern: /co-authored-by:.*\bcopilot\b|assisted-by:.*\bcopilot\b/i, toolId: 'copilot' },
  {
    pattern: /co-authored-by:.*\bcursor\b|generated with cursor\b|via cursor\b/i,
    toolId: 'cursor',
  },
  { pattern: /co-authored-by:.*\b(windsurf|codeium)\b/i, toolId: 'windsurf' },
  { pattern: /co-authored-by:.*\baider\b|via aider\b/i, toolId: 'aider' },
  { pattern: /co-authored-by:.*\btabnine\b/i, toolId: 'tabnine' },
  { pattern: /co-authored-by:.*\b(cody|sourcegraph)\b/i, toolId: 'cody' },
  { pattern: /co-authored-by:.*\b(amazon-?q|amazonq)\b/i, toolId: 'amazonq' },
  {
    // @google.com 単独では判定しない（人間の Google 社員 co-author を誤検出するため）。
    // 明示的な gemini 表記がある場合のみ検出
    pattern: /co-authored-by:.*\bgemini\b|assisted-by:.*\bgemini\b/i,
    toolId: 'gemini',
  },
  { pattern: /co-authored-by:.*\bdevin\b|via devin\b/i, toolId: 'devin' },
  { pattern: /co-authored-by:.*\bsweep\b/i, toolId: 'sweep' },
  // ---- 汎用AIマーカー（AI とは判るがツール特定不能 = 正当な unknown）----
  { pattern: /co-authored-by:\s.*\d+\+[^@]+@users\.noreply\.github\.com/i, toolId: 'unknown' },
  { pattern: /co-authored-by:\s.*noreply@/i, toolId: 'unknown' },
  // 'with' を含めると通常のコード生成ツール（openapi-generator/protoc等）の
  // commit message を誤検出するため 'by' のみに限定
  { pattern: /generated by/i, toolId: 'unknown' },
  { pattern: /\[ai\]/i, toolId: 'unknown' },
  { pattern: /🤖/, toolId: 'unknown' },
]

export function detectAiSignal(message: string, authorLogin: string | null): AiDetection {
  if (authorLogin) {
    for (const s of BOT_SIGNALS) {
      if (s.pattern.test(authorLogin)) return { isAi: true, toolId: s.toolId }
    }
  }
  for (const s of MESSAGE_SIGNALS) {
    if (s.pattern.test(message)) return { isAi: true, toolId: s.toolId }
  }
  return { isAi: false, toolId: 'unknown' }
}
