import type { GitHubCommit } from "~/github/types";
import type { CoauthorAnalysis } from "./types";

const AI_COAUTHOR_PATTERNS = [
	/co-authored-by:\s.*\b(claude|copilot|cursor|aider|codeium|tabnine|amazon-q)\b/i,
	/co-authored-by:\s.*@anthropic\.com/i,
	/co-authored-by:\s.*@github\.com/i,
	/co-authored-by:\s.*noreply@/i,
];

const AI_MESSAGE_PATTERNS = [/generated by/i, /\[ai\]/i, /🤖/];

const AI_BOT_PATTERNS = [
	/\[bot\]$/,
	/^devin-ai/,
	/^sweep-ai/,
	/^dependabot/,
	/^renovate/,
	/^github-actions/,
];

export function isAiCommit(
	message: string,
	authorLogin: string | null,
): boolean {
	if (authorLogin && AI_BOT_PATTERNS.some((p) => p.test(authorLogin))) {
		return true;
	}
	if (AI_COAUTHOR_PATTERNS.some((p) => p.test(message))) {
		return true;
	}
	return AI_MESSAGE_PATTERNS.some((p) => p.test(message));
}

export function analyzeCoauthor(commits: GitHubCommit[]): CoauthorAnalysis {
	const totalCommits = commits.length;
	if (totalCommits === 0) {
		return { totalCommits: 0, aiCommits: 0, rate: 0 };
	}
	const aiCommits = commits.filter((c) =>
		isAiCommit(c.message, c.author?.user?.login ?? null),
	).length;
	return {
		totalCommits,
		aiCommits,
		rate: aiCommits / totalCommits,
	};
}
